### ISSUE TITLE
Use questions

### ISSUE THREAD

**Issue by StevesHarrington** [maskrs/DBD_AFK_TOOL#1]
He will look up. The left click starting frequency is very low, and it is difficult to hit people because he keeps rotating 360 °

**Comment by maskrs** [comment]
我不止开发了一套动作
所有动作都经过设计，本套动作具有它的合理性。 
要我给你解答吗？  
1. 抬头防止鞭炮、闪光弹之类的道具
2. 360°旋转闪避手电
3. A人的问题：你应该搞明白脚本的目的，血点？不是的，脚本挂机不是为了血点，为了血点请去PY。A人反而会浪费大量时间从而降低效率，本脚本最大程度规避了A人的几率。

**Comment by MLy2580** [comment]
懂了，之前见多了挂机杀手，以为是刷血点，原来是为了升级。
谢谢解答

**Comment by qjunx** [comment]
能添加后台功能吗？人比较小白不会过虚拟机的easy检测
