### ISSUE TITLE
报错反馈

### ISSUE THREAD

**Issue by wyang97** [maskrs/DBD_AFK_TOOL#2]
加载字库错误，请检查设置的字库路径是否正确。脚本无法正常运行，返回主页面就会跳出这个报错

**Comment by wyang97** [comment]
感谢您的软件，但想提个建议就是新的脚本出来后应该让用户选择使用老版本作为稳定版或者新版本，而不是强制更新会比较好一些

**Comment by maskrs** [comment]
> 加载字库错误，请检查设置的字库路径是否正确。脚本无法正常运行，返回主页面就会跳出这个报错

该问题已修复，重新下载即可

**Comment by maskrs** [comment]
> 感谢您的软件，但想提个建议就是新的脚本出来后应该让用户选择使用老版本作为稳定版或者新版本，而不是强制更新会比较好一些

V4.1 版本后已不再强制更新，V4.1.1 自选检查更新，V4.1.2虽然强制检查更新，但可以关闭提示框继续使用
