### ISSUE TITLE
新版本貌似失效了？

### ISSUE THREAD

**Issue by okbyxray** [maskrs/DBD_AFK_TOOL#28]
![qq_pic_merged_1707836865748](https://github.com/maskrs/DBD_AFK_TOOL/assets/107928869/56abfba5-a55f-4d31-a355-e1414cc8d02b)
![qq_pic_merged_1707836851416](https://github.com/maskrs/DBD_AFK_TOOL/assets/107928869/bae40202-3a53-46b7-80e5-d910ee7e2dfa)
开始游戏的位置变了，脚本失效了？

**Comment by okbyxray** [comment]
细节配置什么的都是按wiki来的

**Comment by maskrs** [comment]
工具随游戏版本更新，尚未失效。可以加QQ群728284728 交流



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月13日(周二) 晚上11:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [maskrs/DBD_AFK_TOOL] 新版本貌似失效了？ (Issue #28)




 
qq_pic_merged_1707836865748.jpg (view on web)
 qq_pic_merged_1707836851416.jpg (view on web)
 开始游戏的位置变了，脚本失效了？
