### ISSUE TITLE
感谢作者的技术贡献！不过在半夜或凌晨使用脚本人数似乎足以相比真实玩家？匹配到辅助屠夫的比例极大增加了

### ISSUE THREAD

**Issue by LincolnYe** [maskrs/DBD_AFK_TOOL#6]
经过匹配测试，在游戏非活跃时段，遇到辅助屠夫的概率最高可达80%，经常需要尝试三把左右才能遇到真实屠夫，一半以上的屠夫特征是赛后自动发thx，使用上加速器切换到韩服或东南亚服有所缓解但仍然有不少几率碰到（可能30%？），日服更高一点，不过现在似乎无法在进入战局前判断是否为脚本屠夫？
以上是常玩萌新人类玩家的一点个人体验，不知其他地区或段位的人是否有相同情况。

希望能能引起作者的一点关注，十分感谢！：）

**Comment by maskrs** [comment]
这种情况只会出现在低隐藏分，我在高隐藏分对局中从未匹配到任何挂机屠夫。
建议尽快提升隐藏分，以摆脱这种局面
