### ISSUE TITLE
与房主断开链接

### ISSUE THREAD

**Issue by YunnrEX** [maskrs/DBD_AFK_TOOL#9]
我使用这个脚本的时候，经常出现与房主断开连接，然后脚本就不动了，不能继续进行循环对局挂机，有什么解决办法吗，不知道是不是分辨率问题，我的分辨率2560x1600（16：10笔记本），昨天晚上挂机一晚上，就打了三局左右（按经验提升估算的），然后就在我睡着的时候出现了与房主断开连接，就停了。

**Comment by Sinspiren** [comment]
首先感谢大佬的脚本，一直用的挺好的。我也是4.1.8之后才出的问题，16：9 是2k屏， 我看了下似乎是有人载游戏的时候拔线，弹出这个窗口后脚本不知道怎么办， 没去点ok造成的。估计是改ui后 这个按钮位置不同了？

**Comment by maskrs** [comment]
如果反馈最好带有截图，有些情况我并没有数据，所以暂时无法修复。

**Comment by maskrs** [comment]
> 首先感谢大佬的脚本，一直用的挺好的。我也是4.1.8之后才出的问题，16：9 是2k屏， 我看了下似乎是有人载游戏的时候拔线，弹出这个窗口后脚本不知道怎么办， 没去点ok造成的。估计是改ui后 这个按钮位置不同了？

这也许是其中一个原因，游戏更新后导致原有的断线重连检测机制无法运作。这个重新编写的模块尚未经过大量测试，可能并不稳定。

**Comment by Sinspiren** [comment]
> > 首先感谢大佬的脚本，一直用的挺好的。我也是4.1.8之后才出的问题，16：9 是2k屏， 我看了下似乎是有人载游戏的时候拔线，弹出这个窗口后脚本不知道怎么办， 没去点ok造成的。估计是改ui后 这个按钮位置不同了？
> 
> 这也许是其中一个原因，游戏更新后导致原有的断线重连检测机制无法运作。这个重新编写的模块尚未经过大量测试，可能并不稳定。
![1](https://user-images.githubusercontent.com/37967552/215284993-f9a2af71-1adb-43ba-a133-6eddce9aba39.png)
![2](https://user-images.githubusercontent.com/37967552/215284996-51ee9831-77d4-46db-aa53-e4ceb6f310f0.png)
![3](https://user-images.githubusercontent.com/37967552/215284999-02516e24-c484-41f9-90c8-71f53a9e9747.png)

大佬，这是我今天遇到的，相同问题。
按照顺序1，2，3。 也就是说有两层，第一层说断开连接，第二层是错误代码500.

**Comment by maskrs** [comment]
> 大佬，这是我今天遇到的，相同问题。卡在第一张图。几个小时都没反应。 手动去点的话，流程是顺序1，2，3。 也就是说有两层，第一层说断开连接，第二层是错误代码500，然后才回到结算页面。  

合适的反馈，非常感谢，该问题已修复，现在重新下载即可。。

**Comment by Sinspiren** [comment]
> > 大佬，这是我今天遇到的，相同问题。卡在第一张图。几个小时都没反应。 手动去点的话，流程是顺序1，2，3。 也就是说有两层，第一层说断开连接，第二层是错误代码500，然后才回到结算页面。
> 
> 合适的反馈，非常感谢，该问题已修复，现在重新下载即可。

感谢大佬更新， 试了两天我没遇到任何问题了。 说个题外话， 大佬考不考虑做一个 单独选择某几个杀手的（假如 我只想轮流挂 枪手，小叮当，和威斯克）因为其他杀手不想掉分。

**Comment by maskrs** [comment]
> 感谢大佬更新， 试了两天我没遇到任何问题了。 说个题外话， 大佬考不考虑做一个 单独选择某几个杀手的（假如 我只想轮流挂 枪手，小叮当，和威斯克）因为只想掉这几个杀手的，但是其他杀手不想掉分。  

此功能已经存在，不过目前只存在于开发者版本，短时间内也不会实装发布。
![屏幕截图 2023-01-31 083942](https://user-images.githubusercontent.com/62243896/215629034-2dcf06ce-455e-4243-ba3a-e531a873b56b.png)
